name: "Push to Cachix"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: quickwit-alt-ui-dev
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: nix build .#devShells.x86_64-linux.default --no-link --print-out-paths > /tmp/paths
      - run: cat /tmp/paths | cachix push quickwit-alt-ui-dev
